version: 2
jobs:
  test:
    docker:
      - image: jaredallard/triton-base
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            set -e
            yarn --production=false --frozen-lockfile
            yarn test
  test-integration:
    docker:
    - image: jaredallard/triton-base
    steps:
    - checkout
    - run:
        name: Install Dependencies
        command: |
          set -e

          # Install deps
          apk add --no-cache make ca-certificates bash git openssh curl docker python-dev libffi-dev openssl-dev gcc libc-dev make py-pip
          pip install docker-compose

          # Kubectl and Helm version
          export KUBE_LATEST_VERSION="v1.13.4"
          export HELM_VERSION="v2.13.1"

          # Install kubectl & helm
          wget -q https://storage.googleapis.com/kubernetes-release/release/${KUBE_LATEST_VERSION}/bin/linux/amd64/kubectl -O /usr/local/bin/kubectl
          chmod +x /usr/local/bin/kubectl
          wget -q https://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > /usr/local/bin/helm
          chmod +x /usr/local/bin/helm
    - run:
        name: Run Integration Tests (may take awhile)
        command: |
          set -e
          yarn --production=false --frozen-lockfile
          make tests-integration
  build-push:
    docker:
      - image: docker:18.06.1-ce
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            set -e
            docker build -t app -f .circleci/Dockerfile .
      - run:
          name: Publish Docker Image
          command: |
            set -e
            docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
            case "$CIRCLE_BRANCH" in
              master) export moving_tag="prod"
                ;;
              stage) export moving_tag="beta"
                ;;
              *) export moving_tag="alpha"
                ;;
            esac
            docker tag app "jaredallard/triton-autoscaler:${moving_tag}"
            docker push "jaredallard/triton-autoscaler:${moving_tag}"

workflows:
  version: 2
  build-test-push:
    jobs:
      - test
      - test-integration
      - build-push:
          context: Docker
          requires:
          - test
          - test-integration
          filters:
            branches:
              only:
                - master
                - stage
                - develop