kind: CustomResourceDefinition
spec:
  scope: Namespaced
  version: v1
  group: tritonjs.com
  names:
    shortNames:
    - asw
    kind: AutoScalerWatcher
    plural: autoscalerwatchers
    singular: autoscalerwatcher
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: autoscalerwatchers.tritonjs.com